docs: update examples (#38)
* docs: update examples

* docs: update

* docs: update

* docs: update

* docs: remove date.md

* docs: fix links

diff --git a/.github/workflows/workflow_call_integration_test.yaml b/.github/workflows/workflow_call_integration_test.yaml
--- a/.github/workflows/workflow_call_integration_test.yaml
+++ b/.github/workflows/workflow_call_integration_test.yaml
@@ -21,9 +21,9 @@ jobs:
           go install -ldflags "-X main.version=v1.0.0 -X main.commit=$GITHUB_SHA -X main.date=$(date +"%Y-%m-%dT%H:%M:%SZ%:z" | tr -d '+')" ./cmd/docfresh
       - run: docfresh -v
       - run: docfresh init
-      - run: docfresh run examples/*.md
+      - run: docfresh run README.md examples/*.md
       - run: |
-          if ! git diff --exit-code examples; then
-            echo "::error:: example files are modified" >&2
+          if ! git diff --exit-code README.md examples; then
+            echo "::error:: files are modified" >&2
             exit 1
           fi
